<?php
/*
 * Implements hook_field_info()
 */

function quiz_field_field_info(){
    return array(
        'quiz_field' => array(
            'label' => t('Quiz Questins'),
            'description' => t('Various types of questions'),
            'default_widget' => 'quiz_field_custom_widget_read_aloud',
            'default_formatter' =>'quiz_field_custom_formatter_read_aloud',
        ),
    );
}

/*
 * Implements hook_widget_info()
 */
function quiz_field_field_widget_info(){
    return array(
        'quiz_field_custom_widget_read_aloud'=> array(
            'label' => t('Read Aloud'),
            'field types' => array('quiz_field')
        ),
        'quiz_field_custom_widget_repeat_sentence' =>array(
            'label' => t('Repeat Sentence'),
            'field types' =>array ('quiz_field'),
        )
    );
}

/*
 * implements hook_field widget_form()
 */
function quiz_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  
    foreach( $field_values  as  $value ){
        $field_values_full +=array(
            $x_value => $value,
        );
        $x_value = $x_value+1;
    }
    $element += array(
        '#type' => 'select',
        '#description' => t('please enter the question'),
        '#options' =>$field_value,

    );
    return array('value' => $element);
}